services:
  postgres:
    container_name: shopper2
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: shopper-challenge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d shopper-challenge"]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    container_name: back-service
    build:
      context: ./back
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://docker:docker@postgres:5432/shopper-challenge
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  front:
    container_name: front-service
    build:
      context: ./front
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - postgres
      - back
