version: '3.8'

services:
  postgres:
    container_name: shopper
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: shopper-challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    container_name: back-service
    build:
      context: ./back
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://docker:docker@postgres:5432/shopper-challenge
    depends_on:
      - postgres
    command: yarn dev

  front:
    container_name: front-service
    build:
      context: ./front
    ports:
      - "80:80"
    depends_on:
      - back
    command: yarn dev --host

volumes:
  postgres_data:
